name : ios-ipa-build

on:
  workflow_dispatch:
jobs:
  build-ios:
    name: ios Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ payload
        working-directory: build/ios/iphoneos

      - name: zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa payload
        working-directory: build/ios/iphoneos

      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"



